[config]
BATCH_BLOCK	= 100000
myPort		= 3000
myDir		= "slkvdb"
isServer	= false
isShell		= false
database	= "badger"

[options]
importFilename = "name2key.csv.bz2"
noMemory	= true # usually necessary for FastCGI configurations

[BuntDB]
dbNamePath	= ""

[log]
Filename	= "gosl.log"
MaxSize		= 10 # MBytes
MaxBackups	= 3,
MaxAge		= 28, # days
